### ISSUE TITLE
__init__() got an unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by rpitonak** [packit/pre-commit-hooks#3]
```
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/rpitonak/.cache/pre-commit/patch1574081540.
black................................................(no files to check)Skipped
Check for added large files..............................................Passed
Check python ast.....................................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check Yaml...............................................................Passed
Detect Private Key.......................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Flake8...............................................(no files to check)Skipped
mypy.................................................(no files to check)Skipped
Check if rebase is needed................................................Failed
hookid: check-rebase

Traceback (most recent call last):
  File "/Users/rpitonak/.cache/pre-commit/repoe5xr3z9z/pre-commit-hooks/check-rebase.py", line 59, in <module>
    exit(main())
  File "/Users/rpitonak/.cache/pre-commit/repoe5xr3z9z/pre-commit-hooks/check-rebase.py", line 22, in main
    ["git", "log", "--format=%s", "-1"], capture_output=True, cwd=path
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

[INFO] Restored changes from /Users/rpitonak/.cache/pre-commit/patch1574081540
```

**Comment by TomasTomecek** [comment]
Happens again:
```
21:21:09  Check if rebase is needed................................................Failed
21:21:09  - hook id: check-rebase
21:21:09  - exit code: 1
21:21:09  
21:21:09  Traceback (most recent call last):
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 59, in <module>
21:21:09      exit(main())
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 22, in main
21:21:09      ["git", "log", "--format=%s", "-1"], capture_output=True, cwd=path
21:21:09    File "/usr/lib64/python3.6/subprocess.py", line 423, in run
21:21:09      with Popen(*popenargs, **kwargs) as process:
21:21:09  TypeError: __init__() got an unexpected keyword argument 'capture_output'
21:21:09  Traceback (most recent call last):
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 59, in <module>
21:21:09      exit(main())
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 22, in main
21:21:09      ["git", "log", "--format=%s", "-1"], capture_output=True, cwd=path
21:21:09    File "/usr/lib64/python3.6/subprocess.py", line 423, in run
21:21:09      with Popen(*popenargs, **kwargs) as process:
21:21:09  TypeError: __init__() got an unexpected keyword argument 'capture_output'
21:21:09  Traceback (most recent call last):
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 59, in <module>
21:21:09      exit(main())
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 22, in main
21:21:09      ["git", "log", "--format=%s", "-1"], capture_output=True, cwd=path
21:21:09    File "/usr/lib64/python3.6/subprocess.py", line 423, in run
21:21:09      with Popen(*popenargs, **kwargs) as process:
21:21:09  TypeError: __init__() got an unexpected keyword argument 'capture_output'
21:21:09  Traceback (most recent call last):
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 59, in <module>
21:21:09      exit(main())
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 22, in main
21:21:09      ["git", "log", "--format=%s", "-1"], capture_output=True, cwd=path
21:21:09    File "/usr/lib64/python3.6/subprocess.py", line 423, in run
21:21:09      with Popen(*popenargs, **kwargs) as process:
21:21:09  TypeError: __init__() got an unexpected keyword argument 'capture_output'
21:21:09  Traceback (most recent call last):
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 59, in <module>
21:21:09      exit(main())
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 22, in main
21:21:09      ["git", "log", "--format=%s", "-1"], capture_output=True, cwd=path
21:21:09    File "/usr/lib64/python3.6/subprocess.py", line 423, in run
21:21:09      with Popen(*popenargs, **kwargs) as process:
21:21:09  TypeError: __init__() got an unexpected keyword argument 'capture_output'
21:21:09  Traceback (most recent call last):
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 59, in <module>
21:21:09      exit(main())
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 22, in main
21:21:09      ["git", "log", "--format=%s", "-1"], capture_output=True, cwd=path
21:21:09    File "/usr/lib64/python3.6/subprocess.py", line 423, in run
21:21:09      with Popen(*popenargs, **kwargs) as process:
21:21:09  TypeError: __init__() got an unexpected keyword argument 'capture_output'
21:21:09  Traceback (most recent call last):
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 59, in <module>
21:21:09      exit(main())
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 22, in main
21:21:09      ["git", "log", "--format=%s", "-1"], capture_output=True, cwd=path
21:21:09    File "/usr/lib64/python3.6/subprocess.py", line 423, in run
21:21:09      with Popen(*popenargs, **kwargs) as process:
21:21:09  TypeError: __init__() got an unexpected keyword argument 'capture_output'
21:21:09  Traceback (most recent call last):
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 59, in <module>
21:21:09      exit(main())
21:21:09    File "/root/.cache/pre-commit/repoicq1p0xz/pre-commit-hooks/check-rebase.py", line 22, in main
21:21:09      ["git", "log", "--format=%s", "-1"], capture_output=True, cwd=path
21:21:09    File "/usr/lib64/python3.6/subprocess.py", line 423, in run
21:21:09      with Popen(*popenargs, **kwargs) as process:
21:21:09  TypeError: __init__() got an unexpected keyword argument 'capture_output'
```
zuul
